import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import BootstrapClient from './bootstrap/BootstrapClient';
import { ImgDataProvider, LoginDataProvider, SocialMediaDataProvider, DataProvider } from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BootstrapClient />
        <DataProvider>
          <LoginDataProvider>
            <SocialMediaDataProvider>
              <ImgDataProvider>
                {children}
              </ImgDataProvider>
            </SocialMediaDataProvider>
          </LoginDataProvider>
        </DataProvider>

        <div className="container text-center">
        </div>
      </body>
    </html>
  )
}
